#!/bin/bash

draw_picture() {
    kitty +kitten icat --silent --stdin no --transfer-mode memory \
        --place "${2}x${3}@${4}x${5}" "$1" </dev/null >/dev/tty
    exit 1
}

case "$1" in
*.jpg | *.jpeg | *.png | *.gif | *.webp | *.bmp)
    draw_picture "$@"
    ;;

*.avi | *.mp4 | *.mkv | *.webm | *.mov)
    ffmpegthumbnailer -i "$1" -s 0 -q 5 -o "/tmp/thumbnail.png"
    draw_picture "/tmp/thumbnail.png" "${@:2}"
    ;;
*)
    if file "$1" | grep -q "text"; then
        bat --color=always --style=numbers "$1"
    else
        hexyl -n 500 "$1"
    fi
    ;;
esac
