hl.on("hyprland.start", function()
    -- Managed by XDG Autostart, check /etc/xdg/autostart/
    -- hl.exec_cmd("nm-applet")
    -- hl.exec_cmd("blueman-applet")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprsunset -t 4500")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("tmux kill-server")
end)
