#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
exec-once = nm-applet &
exec-once = blueman-applet &
exec-once = waybar & hyprpaper
exec-once = hyprsunset -t 4500
exec-once = systemctl --user start hyprpolkitagent
exec-once = dunst # Notification manager

# This is needed because hyprland variables won't be kept in tmux, we have to kill the
# server when launching hyprland
# Remove if not using tmux anymore
exec-once = tmux kill-server


