##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule {
	name = steam-games-xwayland-workspace-1
    match:class = steam_app_.*

    workspace = 1
    content = game
}

windowrule {
	name = steam-games-wayland-workspace-1
	match:class = .*exe$

	workspace = 1
	content = game
}

windowrule {
    name = osu-workspace-1
    match:class = osu!

    workspace = 1
    content = game
}

windowrule {
    name = steam-launcher-w4
    match:class = steam

    workspace = 4
}

windowrule {
    name = discord-w2
    match:class = discord

    workspace = 2
}
